name: jato
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.3
  firebase_core: ^3.5.0
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_bounceable: ^1.1.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/jatoo.png"

flutter:
  assets:
    - assets/icon/
    - assets/image/
  uses-material-design: true
