// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VBuAyblz37_AXyjBT1nGGWVbJdjV0Pw',
    appId: '1:1057068676036:web:1f33ce46203d51b792ea91',
    messagingSenderId: '1057068676036',
    projectId: 'jato-f7915',
    authDomain: 'jato-f7915.firebaseapp.com',
    storageBucket: 'jato-f7915.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6wEPwIcMxZeKOzQVuhjz790FPuips6pM',
    appId: '1:1057068676036:android:f6955dc9e640256b92ea91',
    messagingSenderId: '1057068676036',
    projectId: 'jato-f7915',
    storageBucket: 'jato-f7915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjkLAOUE3HKiQA3muCHL8iUUM6aGonAk',
    appId: '1:1057068676036:ios:ccd7912645c1c62392ea91',
    messagingSenderId: '1057068676036',
    projectId: 'jato-f7915',
    storageBucket: 'jato-f7915.appspot.com',
    iosBundleId: 'com.jato.jato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjkLAOUE3HKiQA3muCHL8iUUM6aGonAk',
    appId: '1:1057068676036:ios:ccd7912645c1c62392ea91',
    messagingSenderId: '1057068676036',
    projectId: 'jato-f7915',
    storageBucket: 'jato-f7915.appspot.com',
    iosBundleId: 'com.jato.jato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4VBuAyblz37_AXyjBT1nGGWVbJdjV0Pw',
    appId: '1:1057068676036:web:726bea42dc97a4a992ea91',
    messagingSenderId: '1057068676036',
    projectId: 'jato-f7915',
    authDomain: 'jato-f7915.firebaseapp.com',
    storageBucket: 'jato-f7915.appspot.com',
  );
}
